name: word_translator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it:
  flutter_bloc:
  equatable:
  dartz:
  shared_preferences:
  flutter_svg: ^1.0.3
  font_awesome_flutter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  textfield_search: 
    git:
      url: https://github.com/maykhid/flutter_textfield_search.git
      ref: list-container-fix

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-